[project]
name = "dh-file-sorter"
version = "0.1.0"
description = "Sorting files in a specific directory by type"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
    "typer>=0.21.1",
]
